version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-manager-api_app
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: books_db
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_ENV: local
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    working_dir: /var/www/html

  db:
    image: mysql:8.0
    container_name: library-manager-api_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
