version: "3.9"

services:
  app:
    build: .
    container_name: library-manager-api-app
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: books_db
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_ENV: local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    working_dir: /var/www/html

  db:
    image: mysql:8.0
    container_name: library-manager-api-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7
    container_name: library-manager-api_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
